# config_docs = https://www.getzola.org/documentation/getting-started/configuration/

title = "It's Chanakya"
description = "A Website about me, for me, built by me!"
base_url = "/"
minify_html = true
# default_language = "en"
