base_url = "https://u-c-s.github.io"
title = "It's Chanakya"
description = "A Website about me, built by me!"
default_language = "en"

#minify_html = true
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
