base_url = "https://thirsty-metal.netlify.app"
default_language = "en"
title = "It's Chanakya"
description = "A Website about me, for me, built by me!"

#minify_html = true
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[extra]
author = "U-C-S"
description = "A Website about me, for me, built by me!"

