[build]
base = "."
publish = "public"
command = "npm run build"

[build.environment]
NODE_VERSION = "17"

[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = false
minify = false

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true
